### ISSUE TITLE
[CHANGE] New design of the homepage

### ISSUE THREAD

**Issue by shawnthompson** [gc-da11yn/user-experience-planning#6]
### Approval needed?

None

### Who shall do the work?

- [ ] I will do it, I want to contribute
- [ ] I am asking for someone else to please do the work

### Additional context

@emmatseng-ux, @oyinR

Could we put the changes needed for the homepage in this issue so we can keep track of it and assign it to someone?

Thanks

**Comment by JulieBB23** [comment]
closing this and we will create a new issue if anything is missing
